### ISSUE TITLE
similar functionality to snapper

### ISSUE THREAD

**Issue by yonicd** [dreamRs/capture#1]
Very nice, seems to duplicate what [snapper](https://github.com/yonicd/snapper) does.

**Comment by pvictor** [comment]
Thanks, I missed that one. I updated README to add a link. I've made this for a specific need in my work, and put it here for convenience.

Victor

PS: I had trouble to capture leaflet maps with polygons with html2canvas, will look at your examples

**Comment by yonicd** [comment]
you had a problem in snapper w leaflets?

**Comment by pvictor** [comment]
Yeah, tried with `html2canvas` directly, but same issue with {snapper}, try this:

```r
world <- rnaturalearth::ne_countries()
library(shiny)
library(leaflet)
shiny::runGadget(
  fluidPage(
    leafletOutput('myMap'),
    snapper::load_snapper(),
    snapper::preview_button(
      ui = '#myMap',
      opts = snapper::config(
        allowTaint = TRUE,
        useCORS = TRUE)
    ),
    snapper::snapper_div()
  ),
  server = function(input, output) {
    map = leaflet(world) %>% 
      addTiles() %>% 
      addPolygons()
    output$myMap = renderLeaflet(map)
  },
  viewer = shiny::browserViewer()
)
```

PS: seems to be a thing of the moment: https://github.com/daattali/shinyscreenshot

**Comment by yonicd** [comment]
Can you open it as an issue in snapper so i can track it in the repo. Thanks

**Comment by yonicd** [comment]
https://javascript.developreference.com/article/14294276/Leaflet+map+polygon+not+shown+on+canvas+when+using+html2canvas

**Comment by pvictor** [comment]
Thanks, solved. Closing this.

**Comment by yonicd** [comment]
What was the solution script ?
