### ISSUE TITLE
How to use the options to filter out DOM elements?

### ISSUE THREAD

**Issue by daattali** [dreamRs/capture#12]
`capture::capture()` has an `options` argument, which accepts a list of options available [here](https://github.com/bubkoo/html-to-image#options). One of the options is `filter` that allows you to filter out cetain DOM elements. I couldn't figure out the syntax of how to use this option with `capture()`?

**Comment by pvictor** [comment]
For the time being, this is not possible, as the expected parameter is a JavaScript function and the options are transmitted in JSON without any specific way of handling this case. I can see if something can be done

**Comment by pvictor** [comment]
You can now pass a javascript function in the filter option like this:

```r
capture(
  selector = "body",
  filename = "filter",
  icon("camera"), "Filter elements",
  options = list(
    filter = "function(node) {
                const exclusionClasses = ['btn-capture'];
                return !exclusionClasses.some((classname) => node.classList?.contains(classname));
              }"
  ),
  format = "png"
)
```

**Comment by daattali** [comment]
Works, thanks!
