### ISSUE TITLE
scale argument does not work with values smaller than 1 (to make image smaller)

### ISSUE THREAD

**Issue by daattali** [dreamRs/capture#13]
This is a duplicate of https://github.com/dreamRs/capture/issues/10 but worded more clearly.

The scale argument seems to work with any value greater than 1, but if I want to make the resulting file **smaller** by using a value of 0.9 or 0.5 for example, the resulting file is a blank canvas.

**Comment by pvictor** [comment]
Currently scale parameter is expected to be an integer, I'll see if we can update the code to use a floating number.

**Comment by daattali** [comment]
It seems to work with non-integer values above 1. `1.1`, `1.5` both work, but `0.9` doesn't

**Comment by pvictor** [comment]
Scale argument now accept floating numbers.
