### ISSUE TITLE
capture_pdf() not working on shinyapps.io

### ISSUE THREAD

**Issue by DrRoad** [dreamRs/capture#3]
The capture_pdf() is working well on my localhost testing but it is not working after my application is deployed to shinyapps.io. After clicking the button to perform the capture_pdf() function, there is red cross shown when hovering on the button but no pdf is generated after clicking the button. No error message shown in the server log.

**Comment by pvictor** [comment]
Hello,

It works here: https://dreamrs.shinyapps.io/capture-pdf/
Can you share the URL of your application ? The code ?
Have you checked the JavaScript console ?

Victor
